name: CI/CD for Dockerized Python Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: git-action

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest

    - name: Run tests
      run: |
        pytest 

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: git-action

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      whit:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: ./git-action
        file: ./git-action/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Image details
      run: |
        echo ${{ steps.build-and-publish.outputs.digest }}